package clorabase.sdk.java;

public enum Reason {
    INVALID_DATATYPE,
    TOO_MANY_REQUESTS,
    DOCUMENT_SIZE_EXCEEDED,
    NOT_EXISTS, File_ALREADY_EXISTS, Storage_NOT_CONFIGURED, FILE_TOO_LARGE, BLOB_NOT_CONFIGURED, UNKNOWN
}
